name: social_media
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # cloud_firestore: ^0.9.7+2 0.16.0
  # image_picker: ^0.6.0+2
  # firebase_storage: ^2.1.0+1 7.0.0
  # firebase_auth: ^0.8.3 0.20.0+1
  # google_sign_in: ^4.0.1+1
  # geolocator: 5.0.1
  # uuid: ^2.0.0
  # image: ^2.0.7
  # animator: 0.1.4
  # path_provider: ^0.5.0+1
  # firebase_messaging: ^4.0.0+1
  # timeago: 2.0.17
  # cached_network_image:
  # flutter_svg:
  # firebase_core: 

  
  cloud_firestore: ^0.16.0
  image_picker: ^0.6.7+21
  flutter_markdown: ^0.5.2
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  google_sign_in: ^4.5.9
  uuid: ^2.2.2
  image: ^2.1.19
  geolocator: ^5.0.1
  animator: ^2.0.2
  path_provider: ^1.6.27
  timeago: ^2.0.17
  share: ^0.6.5+4
  url_launcher: ^5.7.10
  font_awesome_flutter: ^8.11.0
  transparent_image: ^1.0.0
  cached_network_image: 
  firebase_messaging: 
  flutter_svg: 
  firebase_core: 



  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/

    # google_signin_button.png
    # - assets/images/nicubunu_Game_baddie_Sunglasser.svg
    # - assets/images/no-camera-sign.svg
    # - assets/images/earth-and-magnify-glass.svg
    # - assets/images/activity_feed.svg
    # - assets/images/camera-icon.svg 
    # - assets/images/holding_phone.png
    # - assets/images/todo_list_greenAccent.png
